type = "npm"

[release]
release_suffix = "release.4"
github_repo = "EdZava/zv-mcp-gitlab"

[npm]
source_package_json = "packages/gitlab-mcp/package.json"
source_dist = "packages/gitlab-mcp/dist"
release_name = "@edzava/gitlab-mcp"

[npm.bin]
gitlab-mcp = "./dist/src/main.js"
